version: '3'

services:
  go-app:
    build:
      context: ./Go
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  nextjs-app:
    build:
      context: ./Next.js
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  wordpress:
    build:
      context: ./wordpress
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: examplerootpass
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
